import { and, desc, eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { InsertUser, outreachEvents, outreachOptOuts, outreachQueue, outreachTouches, users } from "../drizzle/schema";
import { ENV } from "./_core/env";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); _db = null; } } return _db; }
export async function upsertUser(user: InsertUser): Promise<void> { if (!user.openId) throw new Error("User openId is required for upsert"); const db = await getDb(); if (!db) return; const values: InsertUser = { openId: user.openId }; const updateSet: Record<string, unknown> = {}; for (const field of ["name", "email", "loginMethod"] as const) if (user[field] !== undefined) { values[field] = user[field] ?? null; updateSet[field] = user[field] ?? null; } values.lastSignedIn = user.lastSignedIn ?? new Date(); updateSet.lastSignedIn = values.lastSignedIn; if (user.role !== undefined || user.openId === ENV.ownerOpenId) { values.role = user.role ?? "admin"; updateSet.role = values.role; } await db.insert(users).values(values).onDuplicateKeyUpdate({ set: updateSet }); }
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }
export async function listOutreachQueue(status?: "pending" | "approved" | "rejected" | "sent" | "archived") { const db = await getDb(); if (!db) return []; return db.select().from(outreachQueue).where(status ? eq(outreachQueue.status, status) : undefined).orderBy(desc(outreachQueue.generatedAt)); }
export async function getOutreachItem(id: number) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(outreachQueue).where(eq(outreachQueue.id, id)).limit(1); return result[0]; }
export async function addOutreachEvent(queueId: number, eventType: (typeof outreachEvents.$inferInsert)["eventType"], metadata?: Record<string, unknown>) { const db = await getDb(); if (!db) return; await db.insert(outreachEvents).values({ queueId, eventType, metadata: metadata ? JSON.stringify(metadata) : null }); }
export async function markOptOut(email: string, token: string, reason?: string) { const db = await getDb(); if (!db) return; await db.insert(outreachOptOuts).values({ email: email.trim().toLowerCase(), token, reason: reason ?? null }).onDuplicateKeyUpdate({ set: { reason: reason ?? null } }); }
export async function isOptedOut(email: string) { const db = await getDb(); if (!db) return false; const result = await db.select({ id: outreachOptOuts.id }).from(outreachOptOuts).where(eq(outreachOptOuts.email, email.trim().toLowerCase())).limit(1); return result.length > 0; }
export async function approveOutreachItem(id: number) { const db = await getDb(); if (!db) throw new Error("Database is not configured"); await db.update(outreachQueue).set({ status: "approved", approvedAt: new Date() }).where(and(eq(outreachQueue.id, id), eq(outreachQueue.status, "pending"))); await addOutreachEvent(id, "approved", { mode: "staged_only" }); }
export async function rejectOutreachItem(id: number) { const db = await getDb(); if (!db) throw new Error("Database is not configured"); await db.update(outreachQueue).set({ status: "archived" }).where(and(eq(outreachQueue.id, id), eq(outreachQueue.status, "pending"))); await addOutreachEvent(id, "rejected"); await addOutreachEvent(id, "archived", { reason: "review_rejected" }); }
export async function markOutreachSent(id: number, sentAt = new Date()) { const db = await getDb(); if (!db) throw new Error("Database is not configured"); await db.update(outreachQueue).set({ status: "sent", sentAt }).where(eq(outreachQueue.id, id)); }
export async function scheduleFollowUps(queueId: number, sentAt: Date) { const db = await getDb(); if (!db) throw new Error("Database is not configured"); const delays = [3, 7, 14, 21]; await db.insert(outreachTouches).values(delays.map((delayDays, index) => ({ queueId, touchNumber: index + 2, delayDays, scheduledFor: new Date(sentAt.getTime() + delayDays * 86400000), status: "scheduled" as const }))); }
